### ISSUE TITLE
If there is no nearby locations to put the grave, the items are deleted

### ISSUE THREAD

**Issue by Prospector** [FireBall1725/Graves#10]
Happened to me on a test server. Items all got deleted and there is no grave anywhere. Perhaps at least keep a log of player's stuff so you can load it back in via commands? Or just make the item entities spawn if there's no valid location.

**Comment by FireBall1725** [comment]
That will be a thing soon

**Comment by Sasikaa** [comment]
Oh yes!! I died when creeper blow up, and my gravestone not generating... The Newest version of your mod...

**Comment by FusionLord** [comment]
As of the latest update graves are forced at the location that the player dies at, so this is no longer an issue.
