### ISSUE TITLE
When killed by the players "ghost" a grave is not spawned.

### ISSUE THREAD

**Issue by Lanolin** [FireBall1725/Graves#17]
I've had this issue happen to me on numerous occasions. This may just be the same bug that occurs when there are no valid grave locations. I've had this happen in open areas, so I am reporting this issue independently.

Playing: SMP Unstable 1.8.9 Version 3.0.16

Graves Version 1.8.9-b30-universal

**Comment by FusionLord** [comment]
- A grave doesn't spawn if you don't have any items.
- When killed by the "ghost" any items you have will be added to the current grave.

**Comment by Lanolin** [comment]
I've never received the items back via any method after being killed by my "ghost". This may require further...testing

**Comment by FireBall1725** [comment]
I know that it works on SSP I have tested it many times, it might require more testing on SMP as something might be clearing out the data that is used to store the last grave location

**Comment by FusionLord** [comment]
This issue was fixed with [9b570ec](https://github.com/FireBall1725/Graves/commit/9b570ec48e18a8e84b8cb61370a5a9e5e9b0a89a).
