### ISSUE TITLE
Items lost in the event of a full inventory.

### ISSUE THREAD

**Issue by Lanolin** [FireBall1725/Graves#18]
I've run into this issue on multiple occasions. In the event that I break open a grave all my items rush into my inventory, cleverly placing themselves back where they were when I died. However, if I have literally ANYTHING else in my inventory any items that cannot relocate to their previous position in my inventory just....disappear. 

Playing: SMP Unstable 1.8.9 Version 3.0.16

Graves Version 1.8.9-b30-universal

**Comment by FireBall1725** [comment]
That is weird, are you able to provide me with the mod pack you are using or a list of mods?  When you break the gravestone to get your items back, it just drops them on the ground no different if you broke a chest, so it shouldn't make items poof.

**Comment by FireBall1725** [comment]
and nm, just noticed the pack.  I am blind.

**Comment by Lanolin** [comment]
Hehe, well if it makes bug squashing any easier I've had it most often happen to Thaumcraft wands. (they tend to poof. Thaumaturgy, amirite?)

**Comment by FreneticScribbler** [comment]
Getting this issue on 1.9.4 with a twist - existing items in the inventory get thrown out all over the floor...not ideal, but better than vanishing. 
EDIT: The pack I'm playing isn't using the latest version of Graves...treat report with suspicion.

**Comment by FusionLord** [comment]
@warlordjones That is the intended design, the only way I could do it while restoring the inventory to the original state.

**Comment by FreneticScribbler** [comment]
Understood, its easy enough to work around, I suppose. Could you not just put the item from the grave somewhere else if the slot is already taken, or is restoring items to the same position that essential? (or a third factor, like a strange way of restoring inventory...)

**Comment by FusionLord** [comment]
It was requested that the Inventory state was returned to the same state. I'll look into changing it so less items end up on the ground.

**Comment by FreneticScribbler** [comment]
Alright, I suspected as much. Thanks :)
