### ISSUE TITLE
Cannot stand on coffin after breaking it open.

### ISSUE THREAD

**Issue by Lanolin** [FireBall1725/Graves#19]
I'm not sure if this is a bug or a feature, so I figured I would report it. In the event that a player dies in lava and a grave is placed (which doesn't always happen I should add) the player is unable to stand on the coffin allowing the player to fall back into the lava. Again, I am only bringing this up because I'm not sure if this is intended or not. I love the idea of being able to recover my items in the event of a silly lava death, but not being able to stand on the Coffin after opening it worries me that items will just be instantly destroyed. There is also the issue that graves like to displace blocks. If I were to die "inside" a coffin because I fell through it would the grave that is spawned displace the previous grave and destroy my items?

Playing: SMP Unstable 1.8.9 Version 3.0.16

Graves Version 1.8.9-b30-universal

**Comment by FusionLord** [comment]
- When displacing blocks the grave adds those block's dropped item to the grave's items.
- Graves cannot override other graves.
- I will look into the lava issue when i get time.
- as for the collision box on the grave once broken that is a feature.(not fully implemented)

**Comment by Lanolin** [comment]
Excellent, but its no fun to die on your Blood Altar and have runes removed thus nerfing your T6 altar instantly to a T1...

**Comment by FusionLord** [comment]
I can see where that could be annoying, I'll look into it.

**Comment by FireBall1725** [comment]
To note, any of the blocks that are broken by the grave will be inside the grave, as far as the blocks from the blood alter.  I will look at adding blocks to a blacklist so the grave will try to move somewhere else if it would break blocks in that blacklist.  Seems like something that we could add an api for as well for other mods to add their blocks too for the ones that we dont get.

**Comment by Lanolin** [comment]
sounds good to me!

**Comment by FusionLord** [comment]
Changes will be in build [45](http://minecraft.curseforge.com/projects/graves/files/2284614)+
