### ISSUE TITLE
Block may be immediately broken, if player dies in explosion

### ISSUE THREAD

**Issue by boq** [FireBall1725/Graves#2]
Vanilla explosion works in following way:
- Select positions to explode (resistance done for non-air blocks). Air blocks will be included.
- Deal damage to players. This is where player dies and grave is spawned.
- Destroy all exploded positions, including previously air-now-grave block - this time without resistance check.

So if player dies in explosion, grave may be destroyed in the same tick.

PS. I had same problem in OpenBlocks, fixed it by delaying block place at the end of tick. But it looks like 1.8.9 has better options, like `Block.onBlockExploded`.

**Comment by FireBall1725** [comment]
I will test it some more with explosions, it shouldn't be able to be exploded, I did test that with TNT, but I didn't test it being placed because of an explosion.

**Comment by FireBall1725** [comment]
In b10 i think this issue is fixed, im overriding Block.onBlockExploded, and not setting it to air.
