### ISSUE TITLE
Forge 1727 Might cause render issue

### ISSUE THREAD

**Issue by FireBall1725** [FireBall1725/Graves#20]
FTB Unstable, running Forge 1727 is causing the graves not to render and it is just an empty block.  Need to see if this is a bug with unstable or a problem with forge.

**Comment by FusionLord** [comment]
Headstone or grave?

**Comment by FireBall1725** [comment]
Both, but only seems to be on FTB One, can't reproduce it.

**Comment by FireBall1725** [comment]
Issue was FTB One related
