### ISSUE TITLE
Grave destroyed Blood Altar

### ISSUE THREAD

**Issue by DeathOfTime** [FireBall1725/Graves#23]
Modpack: FTB Unstable 1.8.9 v. 3.0.23 
Forge: forge-1.8.9-11.15.1.1727-universal.jar
Graves: graves-1.8.9-b37-universal.jar
Some possible cross-mod interactions:BloodMagic-1.8.9-2.0.0-253-ss.jar

While playing on a server setup of Unstable my little brother died while filling a blood altar. When He retrieved the stuff from the gravestone he got the blank rune, and the dirt block under the blood altar back. The blood altar was no where to be found.

The server was on my PC. It is roughly five feet from his PC. I was playing on my PC on the server as well. I was in the Nether collecting resources.

I will try to attach the notes I made and used to setup the server.
[000 Unstable 1.8.9 Server Setup Notes.txt](https://github.com/FireBall1725/Graves/files/125455/000.Unstable.1.8.9.Server.Setup.Notes.txt)

**Comment by FireBall1725** [comment]
Yeah, I am aware of this issue, working on adding blacklists for blocks, so some blocks wont be replaced.  This will be in a future release.

**Comment by robertm1771** [comment]
Had same problem hope you can get it fixed ASAP thanks for the mod
