### ISSUE TITLE
Items should be retrieved from the grave itself, coffins should be toggleable

### ISSUE THREAD

**Issue by ghost** [FireBall1725/Graves#24]
See title, coffins are unnecessary and cause a lot of problems with replacing tiles.  The old gravestone mod (http://www.curse.com/mc-mods/minecraft/237071-gravestones-die-classy) was probably the most elegant implementation of graves that I've seen.  I recommend checking it out to see how those worked

**Comment by FireBall1725** [comment]
It doesn't replace tiles, https://github.com/FireBall1725/Graves/blob/master/src/main/java/com/fireball1725/graves/helpers/SafeBlockReplacer.java#L22

also, the mechanics of this mod is a WIP, and there is going to be more to come with the coffins in future

**Comment by FireBall1725** [comment]
I will add this option, but if you turn off coffins then the items will be in the headstone

**Comment by ghost** [comment]
That's exactly what I wanted, thank you very much.
