### ISSUE TITLE
Integration with Chisel & Bits

### ISSUE THREAD

**Issue by Josephur** [FireBall1725/Graves#25]
I think it would be cool if a player could design their own gravestone that's used when they die if Chisel & Bits is present and they have set it, I know this is minor.. but I think it would be an awesome feature that no other gravestone mod has :)

**Comment by FusionLord** [comment]
Added in the latest version, make you chisel design, pick it up and right click your headstone with that item in hand, you can return to the default with right click.

**Comment by Josephur** [comment]
Fusion, you are awesome I didn't think it would make it into the mod! :)

**Comment by FusionLord** [comment]
Thanks!
