### ISSUE TITLE
No grave created in Roguelike Dungeons

### ISSUE THREAD

**Issue by Josephur** [FireBall1725/Graves#27]
I've had this happen several times now, I use the mod called Roguelike Dungeons on my server, and for some reason graves do not like to be created in there (happens often).

http://minecraft.curseforge.com/projects/roguelike-dungeons
Using version 1.8.9 - 1.4.5 of Roguelike Dungeons

**Comment by FusionLord** [comment]
What version of Graves?

**Comment by Josephur** [comment]
graves-1.8.9-b39

**Comment by FusionLord** [comment]
Why did you close this issue?

**Comment by Josephur** [comment]
I didn't?  Or if I did it was on complete accident :)

**Comment by FusionLord** [comment]
Must have been the "Close and Comment" button.

**Comment by RyanP1991** [comment]
From what I have seen, the graves get created in an area that it is safe to spawn so in theory could be anywhere in the dungeon.

**Comment by FusionLord** [comment]
@RyanP1991 is correct in this situation if we cannot find a safe position to put the grave we put it on the top block above where you died.
