### ISSUE TITLE
1.8.9-Crash w/ b6

### ISSUE THREAD

**Issue by WenXin20** [FireBall1725/Graves#3]
Crashes w/ java.lang.ClassNotFoundException: com.fireball1725.graves.Graves
Crash Log: (https://github.com/FireBall1725/Graves/files/95171/crash-2016-01-18_13.04.06-client.txt)

**Comment by FireBall1725** [comment]
Such a weird crash log.  What version of Forge are you using?

**Comment by WenXin20** [comment]
Forge 1.8.9 11.15.0.1705

**Comment by FireBall1725** [comment]
Can you try it with the latest version i uploaded, b7.  Let me know if you are still having this crash.

**Comment by WenXin20** [comment]
It doesn't crash, it seems to be fixed.

**Comment by FireBall1725** [comment]
ok, glad to hear, thanks.
