### ISSUE TITLE
Last ditch graves are all sky-high if you haven't fallen out of the world.

### ISSUE THREAD

**Issue by Phylogeny** [FireBall1725/Graves#32]
The 'less than' in [line 122 of the SafeBlockReplacer](https://github.com/FireBall1725/Graves/blob/master/src/main/java/com/fireball1725/graves/helpers/SafeBlockReplacer.java#L122) should be a 'greater than'. I just noticed it in a recent stream video. At least you [_said_ 'greater than' while typing it](https://twitch.tv/fireball1725dev/v/45308251?t=41m55s). :stuck_out_tongue:

**Comment by FireBall1725** [comment]
Very good catch!  Yes, you are correct that it should be > not <.  I will get this updated.

**Comment by Phylogeny** [comment]
:smile:

**Comment by FusionLord** [comment]
Fixed with [5c54ff8](https://github.com/FireBall1725/Graves/commit/5c54ff82ee374583aa4707b5c1fd958e513dabdc)
