### ISSUE TITLE
upon death invisible inaccessible grave is created SMP

### ISSUE THREAD

**Issue by Circuitree** [FireBall1725/Graves#33]
Upon death (fall damage, burnt to death, killed by mob) an invisible grave with tombstone is created but inaccessible and "phantom blocks" (acts as if blocks are there, but can't place any blocks in it's place) in SMP (FTB Unstable 1.8 3.0.36; has been an issue since at least v3.0.17).

I've noticed this is not an issue in SSP.
Mod is enabled Client Side and Server Side
All 14 Clients are seeing invisible blocks and are unable to interact with grave to retrieve items

**Versions**
Java: 8.0.66 & 8.0.66 (64-bit)
Forge: 11.15.1.1757
Graves: 1.8.9-b45-universal
Modpack: FTB Unstable 1.8 v3.0.36

[Screenshot](http://imgur.com/3QFkYJa)
[Log from Server](http://pastebin.com/Q13yEedj)

**Comment by FusionLord** [comment]
Was the mod on the server then removed and then re-added? if so this is an issue with Forge otherwise I have no idea what the issue is.

**Comment by FusionLord** [comment]
I haven't heard back from you so I'm going to close the issue if you still have this issue open a new issue.
