### ISSUE TITLE
graves{1.9-b8-universal} crashes dedicated forge server 1.9 build 1804 on startup with nosuchmethod error

### ISSUE THREAD

**Issue by kreezxil** [FireBall1725/Graves#39]
Issue:  graves{1.9-b8-universal} crashes dedicated forge server 1.9 build 1804 on startup with nosuchmethod error

crash report:
https://gist.github.com/ff32dfbc1fb3ccc5527a

fml server latest:
https://gist.github.com/1c8ea12a7271e8849925

**Comment by FusionLord** [comment]
update to forge 1809, Forge is still in alpha and I will not be supporting all versions.
