### ISSUE TITLE
Entity crash when ghost/zombie appears (could be my pc sorry) :]

### ISSUE THREAD

**Issue by vineofthedead** [FireBall1725/Graves#42]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-beta-14.jar)
  LoadingPlugin (RandomThings-MC1.9-3.6.9.jar)
  LoadingPlugin (FastLeafDecay-MC1.9-1.2.jar)
  LoadingPlugin (Bloodmoon-MC1.9-1.4.1.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 4/11/16 5:26 PM
Description: Saving entity NBT

java.lang.NullPointerException: Saving entity NBT
    at com.fireball1725.graves.entity.EntityPlayerZombie.func_70014_b(EntityPlayerZombie.java:389)
    at net.minecraft.entity.Entity.func_70109_d(Entity.java:1548)
    at com.fireball1725.graves.entity.EntityPlayerZombie.func_70109_d(EntityPlayerZombie.java:89)
    at mcp.mobius.waila.api.impl.DataAccessorCommon.getNBTData(DataAccessorCommon.java:137)
    at net.darkhax.wawla.engine.waila.EntityProvider.getWailaOverride(EntityProvider.java:23)
    at mcp.mobius.waila.overlay.RayTracing.getIdentifierEntity(RayTracing.java:122)
    at mcp.mobius.waila.overlay.RayTracing.getTargetEntity(RayTracing.java:74)
    at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:107)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_331_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:336)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.fireball1725.graves.entity.EntityPlayerZombie.func_70014_b(EntityPlayerZombie.java:389)

-- Entity being saved --
Details:
    Entity Type: graves.playerzombie (com.fireball1725.graves.entity.EntityPlayerZombie)
    Entity ID: 11042
    Entity Name: vineofthedead_
    Entity's Exact location: -1897.46, 75.01, 329.30
    Entity's Block location: World: (-1898,75,329), Chunk: (at 6,4,9 in -119,20; contains blocks -1904,0,320 to -1889,255,335), Region: (-4,0; contains chunks -128,0 to -97,31, blocks -2048,0,0 to -1537,255,511)
    Entity's Momentum: -0.11, 0.00, 0.10
    Entity's Passengers: []
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.entity.Entity.func_70109_d(Entity.java:1548)
    at com.fireball1725.graves.entity.EntityPlayerZombie.func_70109_d(EntityPlayerZombie.java:89)
    at mcp.mobius.waila.api.impl.DataAccessorCommon.getNBTData(DataAccessorCommon.java:137)
    at net.darkhax.wawla.engine.waila.EntityProvider.getWailaOverride(EntityProvider.java:23)
    at mcp.mobius.waila.overlay.RayTracing.getIdentifierEntity(RayTracing.java:122)
    at mcp.mobius.waila.overlay.RayTracing.getTargetEntity(RayTracing.java:74)
    at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:107)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_331_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:336)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['vineofthedead_'/60, l='MpServer', x=-1898.93, y=75.83, z=329.63]]
    Chunk stats: MultiplayerChunkCache: 289, 289
    Level seed: 0
    Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (64,64,122), Chunk: (at 0,4,10 in 4,7; contains blocks 64,0,112 to 79,255,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 356668 game time, 480581 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 65 total; [EntityBat['Bat'/10013, l='MpServer', x=-1938.32, y=34.00, z=386.65], EntityPlayerZombie['vineofthedead_'/11042, l='MpServer', x=-1897.46, y=75.01, z=329.30], EntityZombie['Zombie'/9507, l='MpServer', x=-1899.50, y=38.00, z=276.50], EntitySkeleton['Skeleton'/10028, l='MpServer', x=-1818.72, y=58.00, z=322.48], EntityBat['Bat'/10043, l='MpServer', x=-1955.85, y=24.07, z=304.75], EntityCreeper['Creeper'/9532, l='MpServer', x=-1898.23, y=36.00, z=267.48], EntitySheep['Sheep'/4157, l='MpServer', x=-1952.20, y=62.44, z=313.49], EntityVillager['Villager'/9021, l='MpServer', x=-1831.55, y=67.00, z=300.55], EntityPlayerSP['vineofthedead_'/60, l='MpServer', x=-1895.50, y=76.00, z=331.90], EntityVillager['Villager'/9022, l='MpServer', x=-1832.55, y=67.00, z=300.56], EntityVillager['Villager'/9023, l='MpServer', x=-1838.30, y=65.00, z=319.70], EntityVillager['Villager'/9024, l='MpServer', x=-1834.88, y=63.00, z=320.78], EntityVillager['Villager'/9025, l='MpServer', x=-1828.43, y=65.00, z=349.78], EntityVillager['Villager'/9026, l='MpServer', x=-1828.69, y=65.00, z=348.76], EntityCreeper['Creeper'/10562, l='MpServer', x=-1968.50, y=30.00, z=259.50], EntityItem['item.item.arrow'/10820, l='MpServer', x=-1878.65, y=76.00, z=326.88], EntityZombie['Zombie'/10573, l='MpServer', x=-1921.50, y=23.00, z=353.50], EntityCreeper['Creeper'/10578, l='MpServer', x=-1883.50, y=22.00, z=307.50], EntityCow['Cow'/84, l='MpServer', x=-1959.81, y=76.00, z=337.72], EntitySheep['Sheep'/1367, l='MpServer', x=-1905.50, y=86.00, z=360.50], EntityItem['item.item.rottenFlesh'/10839, l='MpServer', x=-1940.77, y=72.00, z=349.39], EntityCow['Cow'/90, l='MpServer', x=-1960.57, y=71.00, z=329.78], EntityZombie['Zombie'/9583, l='MpServer', x=-1954.50, y=79.00, z=265.50], EntitySheep['Sheep'/3194, l='MpServer', x=-1944.21, y=61.11, z=316.45], EntitySpider['Spider'/10362, l='MpServer', x=-1968.50, y=35.00, z=380.50], EntitySkeleton['Skeleton'/10627, l='MpServer', x=-1945.50, y=38.00, z=399.50], EntityCreeper['Creeper'/10375, l='MpServer', x=-1894.50, y=67.00, z=401.50], EntityCow['Cow'/1163, l='MpServer', x=-1966.65, y=74.00, z=343.45], EntityCow['Cow'/8077, l='MpServer', x=-1861.85, y=63.00, z=296.59], EntityPig['Pig'/8078, l='MpServer', x=-1861.50, y=70.00, z=338.75], EntityVillager['Villager'/8079, l='MpServer', x=-1857.54, y=67.00, z=336.93], EntityPig['Pig'/8080, l='MpServer', x=-1866.50, y=68.00, z=353.27], EntityVillager['Villager'/8592, l='MpServer', x=-1834.33, y=63.00, z=319.87], EntitySheep['Sheep'/8081, l='MpServer', x=-1870.69, y=73.00, z=365.76], EntityVillager['Villager'/8593, l='MpServer', x=-1854.72, y=67.00, z=336.49], EntityBat['Bat'/9873, l='MpServer', x=-1880.75, y=46.12, z=258.25], EntityPig['Pig'/7829, l='MpServer', x=-1871.73, y=81.00, z=338.54], EntitySkeleton['Skeleton'/10901, l='MpServer', x=-1948.50, y=10.00, z=366.50], EntityChicken['Chicken'/7833, l='MpServer', x=-1880.89, y=64.00, z=269.51], EntityChicken['Chicken'/7834, l='MpServer', x=-1879.82, y=65.00, z=268.47], EntityChicken['Chicken'/7835, l='MpServer', x=-1888.14, y=64.00, z=270.10], EntityCow['Cow'/7837, l='MpServer', x=-1875.52, y=65.00, z=259.82], EntityItem['item.item.egg'/7839, l='MpServer', x=-1882.81, y=64.00, z=270.14], EntityPig['Pig'/7840, l='MpServer', x=-1874.74, y=75.00, z=326.50], EntityPig['Pig'/9380, l='MpServer', x=-1945.00, y=63.00, z=322.00], EntityZombie['Zombie'/10661, l='MpServer', x=-1882.50, y=34.00, z=277.50], EntitySkeleton['Skeleton'/9638, l='MpServer', x=-1843.14, y=62.25, z=295.87], EntityBat['Bat'/9895, l='MpServer', x=-1946.40, y=18.11, z=284.31], EntityChicken['Chicken'/8118, l='MpServer', x=-1878.49, y=65.00, z=254.87], EntityCreeper['Creeper'/10679, l='MpServer', x=-1851.54, y=60.00, z=333.20], EntityPlayerSP['vineofthedead_'/60, l='MpServer', x=-1898.93, y=75.83, z=329.63], EntityBat['Bat'/10446, l='MpServer', x=-1957.54, y=18.42, z=262.38], EntityCow['Cow'/3281, l='MpServer', x=-1899.15, y=63.00, z=279.17], EntitySkeleton['Skeleton'/10713, l='MpServer', x=-1836.23, y=58.00, z=313.47], EntityCow['Cow'/3290, l='MpServer', x=-1917.20, y=63.00, z=280.53], EntityTippedArrow['Arrow'/9949, l='MpServer', x=-1923.97, y=68.79, z=303.03], EntityEnderman['Enderman'/10723, l='MpServer', x=-1952.50, y=18.00, z=284.50], EntityCreeper['Creeper'/10728, l='MpServer', x=-1972.50, y=11.00, z=366.50], EntityZombie['Zombie'/9706, l='MpServer', x=-1916.50, y=30.00, z=265.50], EntitySkeleton['Skeleton'/9196, l='MpServer', x=-1910.20, y=62.47, z=257.51], EntityHorse['Horse'/1013, l='MpServer', x=-1949.00, y=63.00, z=317.12], EntityPig['Pig'/9717, l='MpServer', x=-1914.50, y=73.00, z=412.69], EntitySheep['Sheep'/1014, l='MpServer', x=-1947.50, y=71.00, z=343.27], EntityCow['Cow'/1015, l='MpServer', x=-1941.18, y=70.00, z=341.43], EntityCreeper['Creeper'/10491, l='MpServer', x=-1927.54, y=15.00, z=405.86]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:409)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2647)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:387)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1045801472 bytes (997 MB) / 2818048000 bytes (2687 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
    IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
    FML: MCP 9.23 Powered by Forge 12.16.0.1862 62 mods loaded, 62 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.9-12.16.0.1862-1.9.jar) 
    UCHIJAAAA   Forge{12.16.0.1862} [Minecraft Forge](forge-1.9-12.16.0.1862-1.9.jar) 
    UCHIJAAAA   additionalbanners{1.1.0.8} [Additional Banners](AdditionalBanners-1.9-1.1.0.8.jar) 
    UCHIJAAAA   animalbikes{1.8} [Animal Bikes](AnimalBikes_1.9.0%2826mar16%29.jar) 
    UCHIJAAAA   AutoSapling{1.3} [AutoSapling](AutoSapling-1.3.1 MC1.9.jar) 
    UCHIJAAAA   basemetals{2.1.1} [Base Metals](BaseMetals_1.9-2.1.1.jar) 
    UCHIJAAAA   bdlib{1.11.0.13} [BD Lib](bdlib-1.11.0.13-mc1.9.jar) 
    UCHIJAAAA   BetterAchievements{0.2.2} [Better Achievements](BetterAchievements-1.9-0.2.2.jar) 
    UCHIJAAAA   BBG{4.0.0} [BetterBedrockGen](BetterBedrockGenerator-1.9.0-3.0.0.jar) 
    UCHIJAAAA   betterbuilderswands{0.5.4} [Better Builder's Wands](BetterBuildersWands-0.5.4-1.9r106+81accd9.jar) 
    UCHIJAAAA   BiomesOPlenty{4.0.2.2008} [Biomes O' Plenty](BiomesOPlenty-1.9-4.0.2.2008-universal.jar) 
    UCHIJAAAA   JEI{3.2.10.185} [Just Enough Items](jei_1.9-3.2.10.185.jar) 
    UCHIJAAAA   BloodMagic{1.9-2.0.0-31} [Blood Magic: Alchemical Wizardry](BloodMagic-1.9-2.0.0-31.jar) 
    UCHIJAAAA   Bloodmoon{1.2} [Bloodmoon](Bloodmoon-MC1.9-1.4.1.jar) 
    UCHIJAAAA   Chameleon{1.9-2.1.3} [Chameleon](Chameleon-1.9-2.1.3.jar) 
    UCHIJAAAA   chameleoncreepers{1.3} [Chameleon Creepers](ChameleonCreepers-1.9-1.3.jar) 
    UCHIJAAAA   chancecubes{1.9-2.0.0.91} [Chance Cubes](ChanceCubes-1.9-2.0.0.91.jar) 
    UCHIJAAAA   chisel{@VERSION@} [Chisel](Chisel-MC1.9-0.0.4.13.jar) 
    UCHIJAAAA   mcmultipart{1.1.1} [MCMultiPart](MCMultiPart-1.1.1-universal.jar) 
    UCHIJAAAA   chiselsandbits{9.13} [Chisels & Bits](chiselsandbits-9.13.jar) 
    UCHIJAAAA   claybucket{1.0} [Clay Bucket](ClayBucket-1.9-1.0.jar) 
    UCHIJAAAA   ElecCore{9} [ElecCore](ElecCore-1.9-1.4.261.jar) 
    UCHIJAAAA   deepresonance{1.1.4beta27} [DeepResonance](deepresonance-1.9.0-1.1.4beta27.jar) 
    UCHIJAAAA   Ding{MC1.9.0v2} [Ding](Ding-MC1.9.0v2.jar) 
    UCHIJAAAA   dldungeonsjdg{1.8.11} [Doomlike Dungeons](DoomlikeDungeons-1.8.11-MC1.9.jar) 
    UCHIJAAAA   poweradvantage{2.0.2} [Power Advantage](PowerAdvantage_1.9.0-2.0.2.jar) 
    UCHIJAAAA   electricadvantage{2.0.1} [Electric Advantage](ElectricAdvantage-2.0.1.jar) 
    UCHIJAAAA   endercrop{1.9-1.2-1836} [Ender Crop](endercrop-1.9.1.2-1858.jar) 
    UCHIJAAAA   enderutilities{0.5.1} [Ender Utilities](enderutilities-1.9-0.5.1.jar) 
    UCHIJAAAA   FastLeaveDecay{1.1} [Fast Leave Decay](FastLeafDecay-MC1.9-1.2.jar) 
    UCHIJAAAA   flatcoloredblocks{mc1.9-v2.2} [Flat Colored Blocks](flatcoloredblocks-mc1.9-v2.2.jar) 
    UCHIJAAAA   pressure{1.3.1.12} [Pressure Pipes](pressure-1.3.1.12-mc1.9.jar) 
    UCHIJAAAA   advgenerators{0.9.20.6} [Advanced Generators](generators-0.9.20.6-mc1.9.jar) 
    UCHIJAAAA   graves{1.9-b8-universal} [Graves Mod](graves-1.9-b8-universal.jar) 
    UCHIJAAAA   hopperducts{1.4.7} [Hopper Ducts](hopperducts-mc1.9-1.4.7.jar) 
    UCHIJAAAA   IronChest{6.0.132.776} [Iron Chest](ironchest-1.9-6.0.132.776.jar) 
    UCHIJAAAA   journeymap{1.9-5.1.6b2} [JourneyMap](journeymap-1.9-5.1.6b2-unlimited.jar) 
    UCHIJAAAA   lteleporters{1.1.1} [Lemon's Simple Teleporters](LemonsSimpleTeleporters-1.1.1.jar) 
    UCHIJAAAA   LunatriusCore{1.1.2.33} [LunatriusCore](LunatriusCore-1.9-1.1.2.33-universal.jar) 
    UCHIJAAAA   mantle{1.9-0.9.4.jenkins114} [Mantle](Mantle-1.9-0.9.4.jar) 
    UCHIJAAAA   testdummy{1.10} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.10.jar) 
    UCHIJAAAA   Morpheus{1.9-3.0.2} [Morpheus](Morpheus-1.9-3.0.2.jar) 
    UCHIJAAAA   planttech{1.4.0} [Planttech](planttech-1.4.0 - 1.9.jar) 
    UCHIJAAAA   playerrugs{1.9-1.3.1} [Player Rugs](PlayerRugs-1.9-1.3.1.jar) 
    UCHIJAAAA   progressiveautomation{1.6.38} [Progressive Automation](ProgressiveAutomation-1.9-1.6.38.jar) 
    UCHIJAAAA   Psi{beta-31} [Psi](Psi-beta-31.jar) 
    UCHIJAAAA   Quark{beta-14} [Quark](Quark-beta-14.jar) 
    UCHIJAAAA   randomthings{3.6.9} [Random Things](RandomThings-MC1.9-3.6.9.jar) 
    UCHIJAAAA   refinedstorage{0.5.5} [Refined Storage](refinedstorage-0.5.5.jar) 
    UCHIJAAAA   xreliquary{1.9-1.3.1.279} [Reliquary](Reliquary-1.9-1.3.1.279.jar) 
    UCHIJAAAA   rftools{4.23beta41} [RFTools](rftools-1.9.0-4.23beta41.jar) 
    UCHIJAAAA   rftoolsdim{4.23beta33} [RFTools Dimensions](rftoolsdim-1.9.0-4.23beta33.jar) 
    UCHIJAAAA   routerreborn{1.9-4.0.1.11b_universal} [Router Reborn](RouterReborn-1.9-4.0.1.11b_universal.jar) 
    UCHIJAAAA   Schematica{1.7.7.144} [Schematica](Schematica-1.9-1.7.7.144-universal.jar) 
    UCHIJAAAA   soulshardstow{1.9-2.3.9-24} [Soul Shards - The Old Ways](SoulShards-TOW-1.9-2.3.9-24.jar) 
    UCHIJAAAA   steamadvantage{2.0.1} [Steam Advantage](SteamAdvantage-2.0.1.jar) 
    UCHIJAAAA   StorageDrawers{1.9-3.1.4} [Storage Drawers](StorageDrawers-1.9-3.1.4.jar) 
    UCHIJAAAA   tconstruct{1.9-2.2.2.jenkins156} [Tinkers' Construct](TConstruct-1.9-2.2.2.jar) 
    UCHIJAAAA   Waila{1.7.0} [Waila](Waila-1.7.0-B2_1.9.jar) 
    UCHIJAAAA   ICSE{1.0.0.0} [I Can See Everything](Wawla-1.9-2.2.0.184.jar) 
    UCHIJAAAA   wawla{2.2.0.178} [What Are We Looking At](Wawla-1.9-2.2.0.184.jar) 
    Loaded coremods (and transformers): 
LoadingPlugin (Quark-beta-14.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.9-3.6.9.jar)
  lumien.randomthings.asm.ClassTransformer
LoadingPlugin (FastLeafDecay-MC1.9-1.2.jar)
  lumien.fastleavedecay.asm.ClassTransformer
LoadingPlugin (Bloodmoon-MC1.9-1.4.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
    GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4338' Renderer: 'Intel(R) HD Graphics'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)

```
List of loaded APIs: 
    * BetterAchievements|API (0.2.2) from BetterAchievements-1.9-0.2.2.jar
    * BloodMagic|API (@VERSION@) from BloodMagic-1.9-2.0.0-31.jar
    * ChiselAPI (0.0.1) from Chisel-MC1.9-0.0.4.13.jar
    * ChiselAPI|Carving (0.0.1) from Chisel-MC1.9-0.0.4.13.jar
    * ChiselsAndBitsAPI (1.8.1) from chiselsandbits-9.13.jar
    * CoFHAPI (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9-1.6.38.jar
    * CoFHAPI|block (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9-1.6.38.jar
    * CoFHAPI|energy (1.8.9R1.2.0B1) from RouterReborn-1.9-4.0.1.11b_universal.jar
    * CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9-1.6.38.jar
    * DLDungeonsAPI (1.1) from DoomlikeDungeons-1.8.11-MC1.9.jar
    * DR-API (1.0.4-Beta) from deepresonance-1.9.0-1.1.4beta27.jar
    * ElecCore|Abilities (#API_VER#) from ElecCore-1.9-1.4.261.jar
    * journeymap|client-api (1.2-SNAPSHOT) from journeymap-1.9-5.1.6b2-unlimited.jar
    * journeymap|client-api-display (1.2-SNAPSHOT) from journeymap-1.9-5.1.6b2-unlimited.jar
    * journeymap|client-api-event (1.2-SNAPSHOT) from journeymap-1.9-5.1.6b2-unlimited.jar
    * journeymap|client-api-model (1.2-SNAPSHOT) from journeymap-1.9-5.1.6b2-unlimited.jar
    * journeymap|client-api-util (1.2-SNAPSHOT) from journeymap-1.9-5.1.6b2-unlimited.jar
    * JustEnoughItemsAPI (3.1.0) from jei_1.9-3.2.10.185.jar
    * McJtyLib (1.9.0-1.8.1beta14) from mcjtylib-1.9.0-1.8.1beta14.jar
    * pressureAPI (1.3.1.12) from pressure-1.3.1.12-mc1.9.jar
    * PsiAPI (2) from Psi-beta-31.jar
    * SchematicaAPI (1.1) from Schematica-1.9-1.7.7.144-universal.jar
    * SchematicaAPI|Events (1.1) from Schematica-1.9-1.7.7.144-universal.jar
    * SoulShardsTOW|API (0.1.5) from SoulShards-TOW-1.9-2.3.9-24.jar
    * StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.4.jar
    * StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.4.jar
    * StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.4.jar
    * StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.4.jar
    * StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.4.jar
    * StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.4.jar
    * StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.4.jar
    * StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.4.jar
    * StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.4.jar
    * WailaAPI (1.3) from Waila-1.7.0-B2_1.9.jar
Launched Version: forge-12.16.0.1862
LWJGL: 2.9.4
OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4338, Intel
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 2x Intel(R) Celeron(R) CPU N2840 @ 2.16GHz
```

**Comment by FusionLord** [comment]
This has been fixed for b9+
