### ISSUE TITLE
Items disappear when breaking graves with a non-empty inventory

### ISSUE THREAD

**Issue by ghost** [FireBall1725/Graves#44]
Forge: 12.16.1.1901
Graves: graves-1.9-b12

When this problem occurs this exception is logged on the server:
[Exception](http://pastebin.com/NThsPb77)

**Comment by FusionLord** [comment]
Full log please

**Comment by ghost** [comment]
http://pastebin.com/R3Z0fm3N

That is the only related entry I found in my logs.

**Comment by FusionLord** [comment]
Full log please.

**Comment by FusionLord** [comment]
Open a new issue if this is still happening when/if you make a new Issue post the entire log
