### ISSUE TITLE
Dying in a smeltery crashes and leaves error grave

### ISSUE THREAD

**Issue by mattk926** [FireBall1725/Graves#45]
If you die in a smeltery from Tconstruct it crashes the game and breaks the smeltery creating an error grave.

crashlog http://pastebin.com/iZw1Juh0

**Comment by mattk926** [comment]
new crashlog on 1.9.4

http://pastebin.com/GwVmiLUp

**Comment by FireBall1725** [comment]
Yeah, @FusionLord this is because your breaking tile entities.  Need to still use my safe block code and not break tile entites.  Breaking TE's is bad... Bad Fusion Lord!!

**Comment by FireBall1725** [comment]
:)

**Comment by FusionLord** [comment]
That isn't the issue the worldObj in the TileEntity is null for some reason. and breaking and replacing TileEntities is not bad.

**Comment by FusionLord** [comment]
@mattk926 for 1.9 the crash is fixed in build [#b13](http://minecraft.curseforge.com/projects/graves/files/2309896) as for the error with 1.9.4 that is a TConstruct error and was fixed with the [2.3.3](http://minecraft.curseforge.com/projects/tinkers-construct/files/2309834) update.

**Comment by mattk926** [comment]
Updated to 2.3.3 Tcon and when i broke the grave to get back my things it crashed with the following report

http://pastebin.com/6AgWxE8x

**Comment by FusionLord** [comment]
@mattk926 Seems that is a server only issue with Tcon please report it [here](https://github.com/SlimeKnights/TinkersConstruct/issues).

**Comment by mattk926** [comment]
For reference the opened issue from Tcon: https://github.com/SlimeKnights/TinkersConstruct/issues/2195

**Comment by FusionLord** [comment]
Thank you!

**Comment by FusionLord** [comment]
[#b14](http://minecraft.curseforge.com/projects/graves/files/2309991) is already uploaded.

**Comment by mattk926** [comment]
Was looking at 1.9.4 but i made a 1.9 world and installed b14 but it still seems to be broken when I break the grave. not sure if it is because of tinkers on 1.9 only is version 2.3.1a or not...

http://pastebin.com/T4zdjrsk

**Comment by FusionLord** [comment]
so the

**Comment by FusionLord** [comment]
Are you getting the crash on 1.9.4? with the latest Graves build and 2.3.3 of TCon?

**Comment by mattk926** [comment]
http://pastebin.com/9Q0YAY2e

Correct 1.9.4 B2 and 2.3.3 of tcon. 

it seems to only happen with 1.9 and 1.9.4 when im standing near the controller. if the grave replaces the controller it crashes it when you break the grave. if i stand in the middle of the smeltery and the grave only replaces the bottom blocs of the smeltery it doesn't appear to crash...

**Comment by FusionLord** [comment]
@mattk926 can you test [1.9.4 #b3](http://minecraft.curseforge.com/projects/graves/files/2310025) please.

**Comment by mattk926** [comment]
@FusionLord Looks great seems to be fixed in B3. Thanks for the prompt replies!

**Comment by FusionLord** [comment]
no problem gonna fix in the 1.9 and 1.10 versions.
