### ISSUE TITLE
Ender Dragon erases grave blocks.

### ISSUE THREAD

**Issue by Rosethorns** [FireBall1725/Graves#48]
Ender dragon erases grave blocks she flies through, along with the ability to get your stuff back.

Needs some for of protection from the ender dragon.

**Comment by FusionLord** [comment]
This has been fixed in the following builds:
-  1.9 - [#b16](http://minecraft.curseforge.com/projects/graves/files/2311707)
-  1.9.4 - [#b4](http://minecraft.curseforge.com/projects/graves/files/2311705)
-  1.10.x - [#b3](http://minecraft.curseforge.com/projects/graves/files/2311709)
