### ISSUE TITLE
Grave not spawning

### ISSUE THREAD

**Issue by JorVaCoding** [FireBall1725/Graves#49]
If a player dies below y=0, a grave doesn't spawn at all and the items are permanently gone
Version: Graves 1.9.4-b1

**Comment by FusionLord** [comment]
Fixing now.

**Comment by FusionLord** [comment]
Fixed in the following builds:
-  1.9 - [#b17](http://minecraft.curseforge.com/projects/graves/files/2311712)
-  1.9.4 - [#b5](http://minecraft.curseforge.com/projects/graves/files/2311714)
-  1.10.x - [#b4](http://minecraft.curseforge.com/projects/graves/files/2311716)
