### ISSUE TITLE
Death with soulbound tools results in a duplicate

### ISSUE THREAD

**Issue by utoc** [FireBall1725/Graves#51]
Hello!

This bug is very simple: When the EnderIO enchant soulbound is applied to a sword/pick etc and the player dies, the item is returned to their inventory when they respawn, however, the graves mod also gives them a duplicate in their grave when broken.

I'm using:
    Graves 1.10-b13
    FML 1.10.2-12.18.0.2008
    MC 1.10.2

Let me know if you need any additional information.

**Comment by FusionLord** [comment]
Strange this was fixed in build 13...

**Comment by utoc** [comment]
If it helps at all, here is a screenshot: http://imgur.com/a/NuMqK.  Sword 1 was in my inventory upon death, sword 2 in my grave.

**Comment by FusionLord** [comment]
Issue is fixed in 1.10.2b16 also lots has changed. :)
