### ISSUE TITLE
Players kicked on server join

### ISSUE THREAD

**Issue by mezz** [FireBall1725/Graves#54]
The latest version references client-only stuff on the server, causing any player who joins to be kicked instantly.
Here's the log from the server:
http://pastebin.com/yYGXDeMC

Here's the change that caused it.
https://github.com/FireBall1725/Graves/commit/d9d871f69ecf551aff6b4325705007be90d72514#diff-a6713d8afa6d5039ce37d81b80fb3142R202

Please test this mod much more thoroughly. Graves mods MUST be incredibly stable, simple, and well tested. Players really depend on it working as intended.

**Comment by FusionLord** [comment]
Thanks mezz Fixed and tested b25+.
