### ISSUE TITLE
1.10.2 Graphical glitch

### ISSUE THREAD

**Issue by dcaster19** [FireBall1725/Graves#57]
**Bug:** Graphical Glitches cause by Graves
Version: Graves-1.10.2-b27-universal

**Screenshot**: http://imgur.com/RF8HxFs

So I first noticed this glitch in FTB unstable and then twice later on in my own private pack and I **think** I've narrowed it down to Graves. I appears to happen when the Headstones that are spawned in world fail to load correctly and it fails to render the player head on the Headstone. It seems to affect water and entities in world as well as other Headstone player head models. Each time I had this happen a Headstone without a player head was in my field of view. I tried reloading the chunks with F3+A but that failed to work resolve the issue only shutting down my SSP world or breaking the offending Headstone stopped the glitch. 

**Reproducing the glitch:** 
As of writing this I haven't been able to reproduce the glitch reliably. I made an instance with just Forge and Graves installed and default video settings.  I've tried loading and reloading chunks with Headstones in them to reproduce it.  The closest I've come to reproducing the glitch is placing down a Headstone by an ocean/water and for a split second when it is trying to render the player head the water glitches. 

I'll try to get you more screenshots with F3 active next time it happens.

**Comment by FusionLord** [comment]
I know what the issue is and I will fix it tomorrow, thank you for reporting this issue.
