### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by K4N0** [FireBall1725/Graves#61]
Graves-1.10.2-b28-universal.jar 
A grave appears after i die but if i break it with my hand or wooden pickaxe i have had no luck in getting my stuff back just a grave. Is there a certain harness to the grave, such as can only be broken with a iron pickaxe? right clicking the grave does nothing.

**Comment by FusionLord** [comment]
There shouldn't be, I'll take a look when I get Home from work, Might be a change with forge as breaking with your hands worked fine.

**Comment by FusionLord** [comment]
Post your logs, it may not have crashed but it'll have information I need.
