### ISSUE TITLE
[1.10.2] Dragon voids stuff

### ISSUE THREAD

**Issue by MakerTim** [FireBall1725/Graves#63]
Hey, i died by the enderdragon, but the dragon flew trough my stuff
now is the grave gone with my stuff

did tried to generate one after that one, and broke it but no stuff :/

P.S. is it really gone? or is there a way still?

**Comment by FusionLord** [comment]
Unfortunately it is gone... I swear I fixed this, what I'll take a look ASAP!

**Comment by FusionLord** [comment]
Items being voided was vanilla, graves cannot be destroyed by the dragon.
