### ISSUE TITLE
[1.10] Graves Go Transparent & @FINGERPRINT@ Error

### ISSUE THREAD

**Issue by Frost-Skyder** [FireBall1725/Graves#64]
For some reason, the graves in the mod randomly will go transparent sometimes. I also get a "@FINGERPRINT@" Error on my server console. I don't know if they are related, or what is causing this. I've tried redownloading the mod with no success.
![2016-10-10_18 15 44](https://cloud.githubusercontent.com/assets/22758670/19256015/0c30a494-8f18-11e6-8e15-194b67d1668f.png)

![screen shot 2016-10-10 at 6 17 10 pm](https://cloud.githubusercontent.com/assets/22758670/19256001/f097f462-8f17-11e6-8614-fc94d58e2041.png)

**Comment by FusionLord** [comment]
This is an old unsupported version of the mod and is provided as is.
