### ISSUE TITLE
new world crashes upon being made

### ISSUE THREAD

**Issue by redgoblin88** [FireBall1725/Graves#67]
on a server i was on, i was getting terrible lag so to find out what was causing it i decided to make a new superflat world but with structures OFF, but upon creating it the game seemed tofreeze, after a while i noticed the consol said "shutting down" so i went to see why and apparently something caused it to crash. upon looking at the crashlog i noticed:
"at com.fireball1725.graves.common.world.WorldGeneration.generate(WorldGeneration.java:36)
at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)" 

so i assume its graves which crashed me

[crash-2017-01-04_13.46.20-server.txt](https://github.com/FireBall1725/Graves/files/684787/crash-2017-01-04_13.46.20-server.txt)

**Comment by FusionLord** [comment]
This is due to a failure of acquiring this list https://raw.githubusercontent.com/FusionLord/FusionLordsPatrons/master/webassets/patrons.json

**Comment by FusionLord** [comment]
This will be fixed in the next version, until then, you should just be able to regenerate the world.
