### ISSUE TITLE
Cannot get property PropertyDirection

### ISSUE THREAD

**Issue by Sasikaa** [FireBall1725/Graves#8]
I'm finding RoguelikeDungeons and try killing the tainted mob. When killing me, teleport back to the Death waypoint. Try crack my graves, crash.

This is my crashlog:
http://pastebin.com/rAGqkcZR

**Comment by FusionLord** [comment]
Duplicate of #6

**Comment by Sasikaa** [comment]
Yes, duplicate, but i use b22 version. Try b23, and perhaps fixing it.

**Comment by FusionLord** [comment]
Yes, build 23 has fixed this issue.
